### ISSUE TITLE
컴파일 오류가 납니다. 어떻게 수정해야 할까요?

### ISSUE THREAD

**Issue by HongKyoungIn** [eazuooz/YamYam_Engine#2]
YamTexture에서 오류가 나는데 어떻게 수정해야할까요?

오류	C1083
- 포함 파일을 열 수 없습니다. 'DirectXTex.h': No such file or directory	YamYamEngine_Window	D:\개인공부\YamYam_Engine-master\YamYamEngine_SOURCE\yaTexture.h	2

오류(활성) E1696	
- 파일 소스을(를) 열 수 없습니다.  "DirectXTex.inl." 
- Editor_Window D:\개인공부\YamYam_Engine-master\YamYamEngine_SOURCE\yaTexture.h	4

오류(활성) E0020 
- 식별자 "ScratchImage"이(가) 정의되어 있지 않습니다.
- Editor_Window D:\개인공부\YamYam_Engine-master\YamYamEngine_SOURCE\yaTexture.h	21

**Comment by eazuooz** [comment]
경로에 한글이 섞여있습니다. 영문 경로로 바꿔서 다시 실행해보시구 안되시는 부분 있으시면 메일주시면 수정해두겠습니다.
eazuooz@gmail.com

또는 vcpkg 통해서 directxtex 버전도 확인해보시면 좋을것 같습니다.
